modLoader="javafml"
loaderVersion="[2,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
logoFile="${icon}"
logoBlur=false
authors="Enchanted_Games"
description='''
${description}
'''

[[mixins]]
config="${id}.mixins.json"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
side="CLIENT"

[[dependencies.${id}]]
modId="sodium"
type="required"
versionRange="${sodium_dep_str}"
side="CLIENT"
